config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'toppages#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

#  get 'signup', to: 'users#new'
  resources :users, only: [:create]

  resources :stops
  resources :buses
  resources :plans, only: [:edit, :update]

  get 'plans/:id', to: 'plans#edit'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bus.rb
class Bus < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }

  has_many :plans, dependent: :destroy
#  has_many :stops, through: :bus_plans, source: :stop
#  has_many :orig_stops, thhrough: :trip_plans, source: :stop
#  has_many :dest_stops, thhrough: :trip_plans, source: :stop
#  has_many :users, through: :trip_plans, source: :user

end

app/models/bus_plan.rb
class BusPlan < ApplicationRecord
  belongs_to :bus
  belongs_to :stop
end

app/models/plan.rb
class Plan < ApplicationRecord
  belongs_to :bus
  belongs_to :stop

#  validates :arrv_time,
#    format: { with: /\A([0-9]|[0-1][0-9]|[2][0-3]):[0-5][0-9]\z/ }
#  validates :dept_time,
#    format: { with: /\A([0-9]|[0-1][0-9]|[2][0-3]):[0-5][0-9]\z/ }
#  validates_time :arrv_time
#  validates_time :dept_time
end

app/models/stop.rb
class Stop < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }

  has_many :plans, dependent: :destroy
#  has_many :trip_plans
#  has_many :buses, through: :bus_plans, source: :bus
#  has_many :orig_stops, thhrough: :trip_plans, source: :stop
#  has_many :dest_stops, thhrough: :trip_plans, source: :stop

end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper  #追記
  include Pagy::Backend
  include PlansHelper

  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end

end

app/controllers/buses_controller.rb
class BusesController < ApplicationController
  before_action :require_user_logged_in
  before_action :sim_time

  def index
      @pagy, @buses = pagy(Bus.order(id: :asc), items: 10)
  end

  def show
    @bus = Bus.find(params[:id])
    @pagy, @stops= pagy(Stop.order(id: :asc), items: 10)
    @simtime = sim_time
    time_prev = "00:00"
    @stops.each do |s|
      plan = @bus.plans.find_or_create_by(stop_id: s.id)
      if time_prev > format_time(plan.arrv_time)
        flash.now[:danger] = '注意：時刻が昇順ではありません'
        break
      end
      time_prev = format_time(plan.dept_time)
    end
  end

  def new
    @bus = Bus.new
  end

  def create
    @bus = Bus.new(bus_params)
    if @bus.save
      flash[:success] = 'バス便を追加しました。'
      redirect_to buses_url
    else
      @pagy, @buses = pagy(Bus.order(id: :desc))
      flash.now[:danger] = 'バス便の追加に失敗しました。'
      render :new
    end
  end

  def edit
    @bus = Bus.find(params[:id])
  end

  def update
    @bus = Bus.find(params[:id])

    if @bus.update(bus_params)
      flash[:success] = 'バス便名は正常に更新されました'
      redirect_to @bus
    else
      flash.now[:danger] = 'バス便名は更新されませんでした'
      render :edit
    end
  end

  def destroy
    @bus = Bus.find(params[:id])
    @bus.destroy
    flash[:success] = 'バス便を削除しました。'
    redirect_to buses_url
  end

  private

  def bus_params
    params.require(:bus).permit(:name)
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :require_user_logged_in
  before_action :sim_time

  def edit
    @plan = Plan.find(params[:id])
    @plan.arrv_time = format_time(@plan.arrv_time)
    @plan.dept_time = format_time(@plan.dept_time)
  end

  def update
    @plan = Plan.find(params[:id])
    p_arrv_time = params[:plan][:arrv_time]
    p_dept_time = params[:plan][:dept_time]

    if !(f_HHMM?(p_arrv_time) && f_HHMM?(p_dept_time))
      flash.now[:danger] = '正しい時刻を入力してください。'
      render_edit
    elsif p_arrv_time.to_time > p_dept_time.to_time
      flash.now[:danger] = '到着時刻は発車時刻より前にしてください。'
      render_edit
    elsif @plan.update(plan_params)
      flash[:success] = '到着・発車時刻を登録しました。'
      redirect_to bus_path(@plan.bus_id, page: params[:page])
    else
      flash.now[:danger] = '到着・発車時刻の登録に失敗しました。'
      render_edit
    end
  end

  private

  def plan_params
    params.require(:plan).permit(:bus_id, :stop_id, :arrv_time, :dept_time)
  end

  def render_edit
    @plan.arrv_time = format_time(@plan.arrv_time)
    @plan.dept_time = format_time(@plan.dept_time)
    render :edit
#    redirect_to request.referer
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end

  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/stops_controller.rb
class StopsController < ApplicationController
  before_action :require_user_logged_in
  before_action :sim_time

  def index
    @pagy, @stops = pagy(Stop.order(id: :asc), items: 10)
  end

  def new
    @stop = Stop.new
  end

  def show
    @stop= Stop.find(params[:id])
  end

  def create
    @stop = Stop.new(stop_params)
    if @stop.save
      flash[:success] = 'バス停を追加しました。'
      redirect_to stops_url
    else
      @pagy, @stops = pagy(Stop.order(id: :asc), items: 10)
      flash.now[:danger] = 'バス停の追加に失敗しました。'
      render :new
    end
  end

  def edit
    @stop = Stop.find(params[:id])
  end

  def update
    @stop = Stop.find(params[:id])

    if @stop.update(stop_params)
      flash[:success] = 'バス停名は正常に更新されました'
      redirect_to @stop
    else
      flash.now[:danger] = 'バス停名は更新されませんでした'
      render :edit
    end
  end

  def destroy
    @stop = Stop.find(params[:id])
    @stop.destroy
    flash[:success] = 'バス停を削除しました。'
    redirect_to stops_url
  end

  private

  def stop_params
    params.require(:stop).permit(:name)
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  before_action :sim_time

  def index
    if logged_in?
      @stops = Stop.order(id: :asc)
    else
      redirect_to login_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show]

  def index
    @pagy, @users = pagy(User.order(id: :asc), items: 25)
  end

  def show
    @user = User.find(params[:id])
  end

#  def new
#    @user = User.new
#  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = '管理者を登録しました。'
      redirect_to root_url
    else
      flash.now[:danger] = '管理者の登録に失敗しました。'
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
  include PlansHelper
end

app/helpers/buses_helper.rb
module BusesHelper
def newestbus
  Bus.order(updated_at: :desc).limit(1)
end

# helper_method :newestbus

end

app/helpers/plans_helper.rb
module PlansHelper
  def format_time(time)
    time ? (l time.to_time) : "00:00"
  end

  def f_HHMM?(time)
    time =~ /\A([0-9]|[0-1][0-9]|[2][0-3]):[0-5][0-9]\z/
  end

  def sim_time
    @simtime = format_time(Time.at(Time.now.to_i*1+9*60*60))
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/buses/_bus_stops.html.erb
<% if stops.any? %>
  <table class="table">
    <tr>
      <th class="text-center">バス停名</th>
      <th class="text-center">到着時刻</th>
      <th class="text-center">発車時刻</th>
    </tr>
    <% stops.each do |stop| %>
      <tr>
        <% plan = @bus.plans.find_or_create_by(stop_id: stop.id) %>
        <th class="text-center"><%= link_to stop.name, edit_plan_path(plan.id, page: @pagy.page), class: "text-decoration-none" %></th>
        <td class="text-center"><%= format_time(plan.arrv_time) %></td>
        <td class="text-center"><%= format_time(plan.dept_time) %></td>
      </tr>
    <% end %>
  </table>
  <%== pagy_bootstrap_nav(@pagy) %>
<% end %>

app/views/buses/_buses.html.erb
<% if buses.any? %>
  <table class="table">
    <thead>
      <tr>
        <th class="text-center">バス便名</th>
      </tr>
    </thead>
    <tbody>
      <% buses.each do |bus| %>
        <tr>
          <th class="text-center"><%= link_to bus.name, bus_path(bus), class: "text-decoration-none" %></th>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%== pagy_bootstrap_nav(@pagy) %>
<% end %>

app/views/buses/edit.html.erb
<% if logged_in? %>
  <div class="row">
    <div class="col-sm-6">
      <h2 class="text-start text-sm-center">バス便名変更</h2>
    </div>
    <div class="col-sm-6">
      <h3 class="text-start text-sm-center">現在時刻 <%= @simtime %></h3>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-6 offset-sm-3">
      <%= form_with(model: @bus) do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>

        <div class="mb-3">
          <%= f.label :name, 'バス便名' %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>

        <%= f.submit '変更', class: 'btn btn-primary w-100' %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/buses/index.html.erb
<% if logged_in? %>
  <div class="row">
    <div class="col-sm-6">
      <h2 class="text-start text-sm-center">運行バス一覧</h2>
    </div>
    <div class="col-sm-6">
      <h3 class="text-start text-sm-center">現在時刻 <%= @simtime %></h3>
    </div>
  </div>

  <div class="row">
    <div class="mx-auto col-md-8">
      <% lastbus = Bus.order(updated_at: :asc).last %>
      <%= link_to 'バス便を末尾に追加', new_bus_path, class: 'btn btn-primary btn-sm' %>
      <% if lastbus %>
        <%= link_to "バス便を末尾から削除", bus_path(lastbus), method: :delete, data: { confirm: "削除しますか？" }, class: 'btn btn-danger btn-sm' %>
      <% end %>
      <div class="mx-auto col-sm-8">
        <%= render 'buses/buses', buses: @buses %>
      </div>
      <%= link_to 'バス便を末尾に追加', new_bus_path, class: 'btn btn-primary btn-sm' %>
      <% if lastbus %>
        <%= link_to "バス便を末尾から削除", bus_path(lastbus), method: :delete, data: { confirm: "削除しますか？" }, class: 'btn btn-danger btn-sm' %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/buses/new.html.erb
<% if logged_in? %>
  <div class="row">
    <div class="col-sm-6">
      <h2 class="text-start text-sm-center">バス便追加</h2>
    </div>
    <div class="col-sm-6">
      <h3 class="text-start text-sm-center">現在時刻 <%= @simtime %></h3>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-6 offset-sm-3">
      <%= form_with(model: @bus) do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>

        <div class="mb-3">
          <%= f.label :name, 'バス便名' %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>

        <%= f.submit '追加', class: 'btn btn-primary w-100' %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/buses/show.html.erb
<% if logged_in? %>
  <div class="row">
    <div class="col-sm-6">
      <h2 class="text-start text-sm-center">運行スケジュール詳細</h2>
    </div>
    <div class="col-sm-6">
      <h3 class="text-start text-sm-center">現在時刻 <%= @simtime %></h3>
    </div>
  </div>

  <div class="row">
    <div class="mx-auto col-md-8">
      <div class="row">
        <div class="col-md-3">
          <h4 class="text-start text-md-end"><%= @bus.name + '便' %></h4>
        </div>
        <div class="col-md-9">
          <%= link_to 'バス便名変更', edit_bus_path(@bus), class: 'btn btn-primary btn-sm' %>
        </div>
      </div>
      <div class="row">
        <div class="col-3">
          <% if Bus.exists?(@bus.id - 1) %>
            <%= link_to '◀前便', bus_path(@bus.id - 1, page: @pagy.page), class: 'btn btn-secondary w-100 btn-sm' %>
          <% end %>
        </div>
        <div class="offset-6 col-3">
          <% if Bus.exists?(@bus.id + 1) %>
            <%= link_to '後便▶', bus_path(@bus.id + 1, page: @pagy.page), class: 'btn btn-secondary w-100 btn-sm' %>
          <% end %>
        </div>
      </div>
      <div class="mx-auto col-sm-8">
        <%= render 'buses/bus_stops', stops: @stops %>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <div class="container-fluid ps-5 pe-5">
      <a class="navbar-brand" href="/">Livebus</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
        <% if logged_in? %>
          <div class="btn-group">
            <ul class="navbar-nav">
              <li class="ms-3"><%= link_to 'Buses', buses_path, class: 'nav-link' %></li>
              <li class="ms-3"><%= link_to 'Stops', stops_path, class: 'nav-link' %></li>
            </ul>
            <button type="button" class="btn btn-dark dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false"><%= current_user.name %></button>
            <ul class="dropdown-menu dropdown-menu-end">
              <li class="dropdown-item"><%= link_to 'Logout', logout_path, method: :delete, class: 'nav-link' %></li>
            </ul>
          </div>
        <% else %>
          <ul class="navbar-nav">
            <li class="nav-item"><%= link_to 'Login', login_path, class: 'nav-link' %></li>
          </ul>
        <% end %>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>Livebus</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
  </head>

  <body data-turbolinks="false">
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/plans/edit.html.erb
<% if logged_in? %>
  <div class="row">
    <div class="col-sm-6">
      <h2 class="text-start text-sm-center">到着・発車時刻変更</h2>
    </div>
    <div class="col-sm-6">
      <h3 class="text-start text-sm-center">現在時刻 <%= @simtime %></h3>
    </div>
  </div>

  <div class="col-sm-8">
    <h3 class="text-start text-sm-center">
      <%= @plan.bus.name %>便
      <%= @plan.stop.name %>バス停
    </h3>
  </div>

  <div class="row">
    <div class="col-sm-2 offset-sm-5">

      <%= form_with(model: @plan) do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>

        <div class="mb-3">
          <%= f.label :arrv_time, '到着時刻' %>
          <%= f.text_field :arrv_time, class: 'form-control text-center' %>
          <%= f.label :dept_time, '出発時刻' %>
          <%= f.text_field :dept_time, class: 'form-control text-center' %>
          <%= hidden_field_tag :page, params[:page] %>
        </div>
        <%= f.submit '変更', class: 'btn btn-primary w-100' %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/stops/_stops.html.erb
<% if stops.any? %>
  <table class="table">
    <thead>
      <tr>
        <th class="text-center">バス停名</th>
      </tr>
    </thead>
    <tbody>
      <% stops.each do |stop| %>
        <tr>
          <th class="text-center"><%= link_to stop.name, stop_path(stop), class: "text-decoration-none" %></th>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%== pagy_bootstrap_nav(@pagy) %>
<% end %>

app/views/stops/_timetable.html.erb
<table class="table">
  <thead>
    <tr>
      <th class="text-center">時</th>
      <th class="text-center">分</th>
    </tr>
  </thead>
  <tbody>
    <% f_1stline = false %>
    <% (0..23).each do |h| %>
      <% busmin = [] %>
      <% Bus.all.each do |bus| %>
        <% bustime = bus.plans.find_or_create_by(stop_id: stop.id).dept_time %>
        <% if bustime && bustime.to_time.strftime("%H") == "%02d" % h %>
          <% busmin.push(bustime.to_time.strftime("%M")+"<br>"+bus.name+"便") %>
        <% end %>
      <% end %>

      <% if f_1stline || !busmin.empty? %>
        <% f_1stline = true %>
        <tr>
          <th class="text-center">
            <%= "%02d" % h %>
          </th>
          <td>
            <div class="row" >
              <% busmin.sort!.each do |m| %>
                <div class="col-2 text-center">
                  <%= m.html_safe %>
                </div>
              <% end %>
            </div>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/stops/edit.html.erb
<% if logged_in? %>
  <div class="row">
    <div class="col-sm-6">
      <h2 class="text-start text-sm-center">バス停名変更</h2>
    </div>
    <div class="col-sm-6">
      <h3 class="text-start text-sm-center">現在時刻 <%= @simtime %></h3>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-6 offset-sm-3">
      <%= form_with(model: @stop) do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>

        <div class="mb-3">
          <%= f.label :name, 'バス停名' %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>

        <%= f.submit '変更', class: 'btn btn-primary w-100' %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/stops/index.html.erb
<% if logged_in? %>
  <div class="row">
    <div class="col-sm-6">
      <h2 class="text-start text-sm-center">バス停一覧</h2>
    </div>
    <div class="col-sm-6">
      <h3 class="text-start text-sm-center">現在時刻 <%= @simtime %></h3>
    </div>
  </div>


  <div class="row">
    <div class="mx-auto col-md-8">
      <% laststop = Stop.order(updated_at: :asc).last %>
      <%= link_to 'バス停を末尾に追加', new_stop_path, class: 'btn btn-primary btn-sm' %>
      <% if laststop %>
        <%= link_to "末尾のバス停 を削除", stop_path(laststop), method: :delete, data: { confirm: "削除しますか？" }, class: 'btn btn-danger btn-sm' %>
      <% end %>
      <div class="mx-auto col-sm-8">
        <%= render 'stops/stops', stops: @stops %>
      </div>
      <%= link_to 'バス停を末尾に追加', new_stop_path, class: 'btn btn-primary btn-sm' %>
      <% if laststop %>
        <%= link_to "末尾のバス停 を削除", stop_path(laststop), method: :delete, data: { confirm: "削除しますか？" }, class: 'btn btn-danger btn-sm' %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/stops/new.html.erb
<% if logged_in? %>
  <div class="text-center">
    <h1>バス停追加</h1>
  </div>

  <div class="row">
    <div class="col-sm-6 offset-sm-3">

      <%= form_with(model: @stop) do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>

        <div class="mb-3">
          <%= f.label :name, 'バス停名' %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>

        <%= f.submit '追加', class: 'btn btn-primary w-100' %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/stops/show.html.erb
<% if logged_in? %>
  <div class="row">
    <div class="col-sm-6">
      <h2 class="text-start text-sm-center">
        <%= @stop.name %>バス停時刻表
      </h2>
    </div>
    <div class="col-sm-6">
      <h3 class="text-start text-sm-center">
        現在時刻 <%= @simtime %>
      </h3>
    </div>
  </div>

  <div class="row">
    <div class="mx-auto col-md-8">
      <div class="row">
        <div class="col-md-9">
          <%= link_to 'バス停名変更', edit_stop_path(@stop), class: 'btn btn-primary btn-sm' %>
        </div>
      </div>
      <div class="row">
        <div class="col-3">
          <% if Stop.exists?(@stop.id - 1) %>
            <%= link_to '◀前バス停', stop_path(@stop.id - 1), class: 'btn btn-secondary w-100 btn-sm' %>
          <% end %>
        </div>
        <div class="offset-6 col-3">
          <% if Stop.exists?(@stop.id + 1) %>
            <%= link_to '次バス停▶', stop_path(@stop.id + 1), class: 'btn btn-secondary w-100 btn-sm' %>
          <% end %>
        </div>
      </div>
      <%= render 'stops/timetable', stop: @stop %>
    </div>
  </div>
<% end %>

app/views/toppages/_realtime_bus.html.erb
<% if stops.any? %>
  <table class="table">
    <thead>
      <tr>
        <th class="text-center">バス停名</th>
        <th class="text-center">バス便名</th>
      </tr>
    </thead>
    <tbody>
      <% pdt = [] %>
      <% f_1stline = false %>
      <% stops.each do |stop| %>
        <tr>
          <th class="text-center">
            <%= link_to stop.name, stop_path(stop.id), class: "text-decoration-none" %>
          </th>
          <% cb = 0 %>
          <td class="text-center">
            <% Bus.all.each do |bus| %>
              <% plan = bus.plans.find_or_create_by(stop_id: stop.id) %>

              <% if !f_1stline && pdt.size <= cb %>
                <% if @simtime < format_time(plan.arrv_time) %>
                  <% f_1stline = true %>
                  <%= bus.name %>便到着待ち<br/>
                <% elsif @simtime < format_time(plan.dept_time) %>
                  <%= bus.name %>便停車中<br/>
                <% end %>
                <% pdt.push(format_time(plan.dept_time)) %>

              <% else %>
                <% if !pdt[cb].nil? && @simtime >= pdt[cb] %>
                  <% if @simtime < format_time(plan.arrv_time) %>
                    <%= bus.name %>便到着待ち<br/>
                  <% elsif @simtime < format_time(plan.dept_time) %>
                    <%= bus.name %>便停車中<br/>
                  <% end %>
                <% end %>
                <% pdt[cb] = format_time(plan.dept_time) %>

              <% end %>
              <% cb += 1 %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/toppages/index.html.erb
<% if logged_in? %>
  <div class="row">
    <div class="col-sm-6">
      <h2 class="text-start text-sm-center">バス運行状況</h2>
    </div>
    <div class="col-sm-6 ">
      <h3 class="text-start text-sm-center">現在時刻 <%= @simtime %></h3>
    </div>
  </div>

  <div class="row">
    <div class="mx-auto col-md-8">
      <%= render 'toppages/realtime_bus', stops: @stops %>
    </div>
  </div>
<% end %>